// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDswGncUKOtGHMD5SspE-El7Yymtt490U4',
    appId: '1:826073515394:web:f359b4de02b8d2bf0c3b9b',
    messagingSenderId: '826073515394',
    projectId: 'zedxecommerce',
    authDomain: 'zedxecommerce.firebaseapp.com',
    storageBucket: 'zedxecommerce.appspot.com',
    measurementId: 'G-5ND57FHECD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpaQx9F3CK9iEvfcUA2WDc5EhLJ_B0Ak4',
    appId: '1:826073515394:android:79ead606414503f90c3b9b',
    messagingSenderId: '826073515394',
    projectId: 'zedxecommerce',
    storageBucket: 'zedxecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBuh21SLZ8uXts2T78-fkSzKffGJCzWg8',
    appId: '1:826073515394:ios:d31ba2e55b5a49560c3b9b',
    messagingSenderId: '826073515394',
    projectId: 'zedxecommerce',
    storageBucket: 'zedxecommerce.appspot.com',
    androidClientId: '826073515394-n93kkas3u11f8ifmenktgjcfgafqnbmg.apps.googleusercontent.com',
    iosClientId: '826073515394-d975dlpt21qoobqlcnhgqf1e5094ho4a.apps.googleusercontent.com',
    iosBundleId: 'com.zedki7.zedxEcommerce',
  );
}
